### ISSUE TITLE
Building for 4.21 or 4.22 fails

### ISSUE THREAD

**Issue by PTS93** [wongfei/ue4-gstreamer#1]
I wanted to build the plugin for 4.21 using Gstreamer 1.4.1 . I followed the instructions, changing my Gstreamer path in the build .cs

Though when I load the project in the Editor I throws this error. Seems it hasn't really build the plugin maybe? Any clues appreciated.

`[2019.04.28-13.20.34:754][  0]LogModuleManager: Warning: ModuleManager: Unable to load module 'E:/Documents/Unreal Projects/ue4-gstreamer/Plugins/GStreamer/Binaries/Win64/UE4Editor-GStreamer.dll' because the file couldn't be loaded by the OS.`

**Comment by PTS93** [comment]
I checked and the file got compiled and sits in said folder. Not sure what is causing the issue then.

**Comment by PTS93** [comment]
Downloaded 4.20 and running into the same issue.

**Comment by wongfei** [comment]
Switched the project version to newer engine (4.22.1), recompiled the plugin and it worked.

"Module couldn't be loaded by the OS" may mean the engine cant find plugin deps (gstreamer dlls).

Check if your system has environment variable:
GSTREAMER_ROOT
or
GSTREAMER_ROOT_X86_64
that points to path where gstreamer lives:
d:\dev\gstreamer1.14.4\1.0\x86_64\

In case it doesn't help, upload the full log: "ue4-gstreamer\Saved\Logs\GStreamerDemo.log"

**Comment by PTS93** [comment]
I did set the GStreamerRoot variable in the GStreamerBuild.cs
I do have a an environment variable that was called GSTREAMER_1.0_ROOT_X86_64
renaming it to either GSTREAMER_ROOT or GSTREAMER_ROOT_X86_64 did not change anything.

I attached my log output.
[GStreamerDemo.log](https://github.com/wongfei/ue4-gstreamer/files/3145525/GStreamerDemo.log)

**Comment by wongfei** [comment]
From log it can't find gstreamer dlls:
`
[2019.05.05-12.40.41:976][  0]LogWindows: Failed to load 'E:/Documents/Unreal Projects/ue4-gstreamer-master/Plugins/GStreamer/Binaries/Win64/UE4Editor-GStreamer.dll' (GetLastError=126)
[2019.05.05-12.40.41:976][  0]LogWindows:   Missing import: libglib-2.0-0.dll
[2019.05.05-12.40.41:976][  0]LogWindows:   Missing import: libgobject-2.0-0.dll
[2019.05.05-12.40.41:976][  0]LogWindows:   Missing import: libgstreamer-1.0-0.dll
[2019.05.05-12.40.41:976][  0]LogWindows:   Missing import: libgstvideo-1.0-0.dll
`

UE4 forces to use static libraries by design and absolute pain in ass when working with third party dlls. To workaround that problem project has Plugins/GStreamerLoader (should be loaded before main plugin) and Plugins/GStreamer. 

GStreamerLoaderModule.cpp
`
	TCHAR RootPath[BufSize] = {0};
	FPlatformMisc::GetEnvironmentVariable(TEXT("GSTREAMER_ROOT_X86_64"), RootPath, BufSize);
	if (!RootPath[0])
	{
		FPlatformMisc::GetEnvironmentVariable(TEXT("GSTREAMER_ROOT"), RootPath, BufSize);
	}
	if (RootPath[0])
	{
		FString BinPath = FPaths::Combine(RootPath, TEXT("bin"));
		SetDllDirectoryW(*BinPath);
	}
`

Maybe GetEnvironmentVariable or SetDllDirectoryW fails.

A. Easy and dirty fix is to copy all dlls from gstreamer bin (d:\dev\gstreamer1.14.4\1.0\x86_64\bin\) to d:\dev\Epic Games\UE_4.22\Engine\Binaries\Win64\

B. Recompile gstreamer as static lib

C. Have some fun with debugger

**Comment by PTS93** [comment]
Oh I must have been blind. I was wondering where it was trying to pull in the dll's
The dirty fix gets it past the loading screen but when open none of the three demo pipelines play anything. I would have expected that at least the noise demo src would show something?

**Comment by PTS93** [comment]
Log says:
```
LogPlayLevel: PIE: World Init took: (0.000631s)
LogPlayLevel: PIE: Created PIE world by copying editor world from /Game/TestLevel.TestLevel to /Game/UEDPIE_0_TestLevel.TestLevel (0.003619s)
LogInit: XAudio2 using 'Speakers (Realtek High Definition Audio)' : 2 channels at 48 kHz using 32 bits per sample (channel mask 0x3)
LogInit: FAudioDevice initialized.
LogLoad: Game class is 'GameModeBase'
LogWorld: Bringing World /Game/UEDPIE_0_TestLevel.TestLevel up for play (max tick rate 0) at 2019.05.05-16.21.37
LogWorld: Bringing up level for play took: 0.000642
LogGStreamer: Error: gst_parse_launch failed -> no element "filesrc"
LogGStreamer: Error: GstPipeline: Init FAILED
LogGStreamer: Error: gst_parse_launch failed -> no element "uridecodebin"
LogGStreamer: Error: GstPipeline: Init FAILED
LogGStreamer: Error: gst_parse_launch failed -> no element "videotestsrc"
LogGStreamer: Error: GstPipeline: Init FAILED
PIE: Play in editor start time for /Game/UEDPIE_0_TestLevel 1,109
```

**Comment by PTS93** [comment]
OK my bad, I must have mis-clicked and downloaded 1.4.4 instead of 1.14.4 ...
Now it is all working, and copying the binaries is not necessary either. Very odd but all good, it was all a user error. Sorry :)
