### ISSUE TITLE
Plugin re-compiles the whole engine when working engine source

### ISSUE THREAD

**Issue by PTS93** [wongfei/ue4-gstreamer#2]
Something very odd that I noticed is that whenever I open the plugin demo project with an engine version that was compiled from source the BuildTool will try to re-compile not only the plugin but the complete engine including the editor.
I haven't tried to let it run through to see if it would work after the complete re-compile as it takes several hours on my machine.

It's not a breaking bug but it would be of course great if it wasn't doing that :)
The fork that made this plugin work on Ubuntu experiences the same issue.

**Comment by wongfei** [comment]
Hard to say, UE4 build system -> epic fail.

Maybe it's broken by non default options in build configuration:
[ue4-gstreamer\Source\GStreamerDemo.Target.cs]
bUseUnityBuild = false;
bUsePCHFiles = false;

Or just bugged, because they have tons of similar problems like:
https://answers.unrealengine.com/questions/701826/bug-automatic-rebuilding-engine-each-time-after-ch.html?childToView=707088#answer-707088

**Comment by PTS93** [comment]
Thanks for the input. I will raise the issue with Epic instead then. Unless there is a flag that a plugin can set to willingly trigger a rebuild it should probably never happen anyway.
